random_seed: 1
output_name: 'simulation_0' # the results will be saved as 'output_name.pickle'

num_agents: 1
num_trials: 40
T_max:  15000

OPTIONS:

  plot_flag: True
  save_activity: False


GEOMETRY:

  bounds_x: [-1, 1] 
  bounds_y: [-1, 1]
  rew_center: [-0.75, -0.75]
  rew_radius: 0.15

  obstacle_1: False
  obstacle_2: False

  starting_position_option: 'origin' # option: 'origin', 'random', 'upper-right'

  obstacle_bounds_x: [-1., -0.8]
  obstacle_bounds_y: [-2, 0.]

  obstacle_bounds_x_2: [0.8, 1]
  obstacle_bounds_y_2: [0., 2.]


CA3:

  bounds_x: [-1, 1]
  bounds_y: [-1, 1]
  space_pc: 0.4
  offset: False

  rho: 0.4 #!
  sigma: 0.4  #!         


CA1:

  bounds_x: [-1, 1] 
  bounds_y: [-1, 1]
  space_pc: 0.4 #!
  offset: False

  rho: 0.4 #!
  sigma: 0.4 #!

  alpha: 1 #!

  # SRM0
  eps0: 100  #!
  tau_m: 20  #!
  tau_s: 5   #!
  chi: -5  #!
  rho0: 60 #!
  theta: 16  #!
  delta_u: 2 #!

  smooth_firing: True #!
  tau_gamma: 50 #!
  v_gamma: 20 #!

  # Weights
  w_min: 0
  w_max: 3

  w_feedforward_init: 'identity' # option: 'convolutional', 'identity', 'random', 'uniform-convolutional'
  max_init: 3. #!
  sigma_init: 0.2 #!

  w_lateral_init: 'None' # options: None

  # Plasticity (BCM)
  plasticity_ON: False

  use_sum: False
  memory_factor: 0.9
  learning_rate: 0.02
  
  weight_decay: 0.
  base_weight: 2.

AC:

  N: 16

  # SRM0
  eps0 : 20 #scaling constant epsp
  tau_m: 20 #membrane time constant
  tau_s: 5 #synaptic time rise epsp
  chi  : -5 #scaling constant refractory effect
  rho0: 0.06 #scaling rate
  theta: 16 #threshold
  delta_u: 5 #escape noise

  smooth_firing: True
  tau_gamma: 20 # decay time for right tale
  v_gamma: 5 # rise time for left tale


  # Weights
  w_min: 1
  w_max: 3

  w_feedforward_init: 'all_equal'
  max_init: 2
  w_lateral_init: 'standard'

  weight_decay: 0.
  base_weight: 2.

  psi: 20 # the higher, the more narrow the range of excitation
  w_minus: -300 # (consider decreasing it)
  w_plus: 100

  # Action
  a0: 0.08 # action
  fixed_step: 0.003 # velocity with 0.003 = 0.3m/s
  use_fixed_step: True

  # Plasticity
  Dopamine: True
  Serotonine: True
  Acetylcholine: True

  A_DA: 0.2 # STDP magnitude of dopamine
  A_5HT: 0.01 # STDP magnitude of serotonin
  A_ACh: 0.01 # STDP magnitude of acetylcholine

  tau_5HT: 10 # Time constant for the STDP window of serotonin
  tau_DA: 10 # Time constant for the STDP window of dopamine
  tau_ACh: 10

  tau_e_DA: 2000 #time constant eligibility trace
  tau_e_5HT: 5000 #time constant eligibility trace for serotonin

  
